# Generated by Django 3.0.2 on 2020-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200421_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedelement',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedelement',
            name='imageurl',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
