# Generated by Django 3.0.2 on 2020-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200423_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetags',
            old_name='url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='feedelement',
            name='fullimage',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2017/03/09/12/31/error-2129569_1280.jpg', unique=True),
        ),
    ]
