# Generated by Django 3.0.2 on 2020-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200424_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedelement',
            name='size',
        ),
        migrations.AddField(
            model_name='feedelement',
            name='height',
            field=models.IntegerField(default=1920),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedelement',
            name='width',
            field=models.IntegerField(default=768),
            preserve_default=False,
        ),
    ]
